# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})
cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})
cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})
cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})
cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})
cw = Appliance.create({name: 'Clothes Washer', load: 800, duration: 1, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_x-jwzEHnAXiyLVaIdCzOCa_lO6Vfrsm-sYX1zrwALbCrS3t7'})
ev = Appliance.create({name: 'Electric Vehicle', load: 1400, duration: 8, image: "https://c1cleantechnicacom-wpengine.netdna-ssl.com/files/2016/07/CarelectricVector-01.jpg"})

hour = Hour.create({period: '12am-1am', efficiency: 3})
hour = Hour.create({period: '1am-2am', efficiency: 4})
hour = Hour.create({period: '2am-3am', efficiency: 5})
hour = Hour.create({period: '3am-4am', efficiency: 1})
hour = Hour.create({period: '4am-5am', efficiency: 1})
hour = Hour.create({period: '5am-6am', efficiency: 1})
hour = Hour.create({period: '6am-7am', efficiency: 4})
hour = Hour.create({period: '7am-8am', efficiency: 5})
hour = Hour.create({period: '8am-9am', efficiency: 5})
hour = Hour.create({period: '9am-10am', efficiency: 4})
hour = Hour.create({period: '10am-11am', efficiency: 5})
hour = Hour.create({period: '11am-12pm', efficiency: 5})
hour = Hour.create({period: '12pm-1pm', efficiency: 5})
hour = Hour.create({period: '1pm-2pm', efficiency: 4})
hour = Hour.create({period: '2pm-3pm', efficiency: 5})
hour = Hour.create({period: '3pm-4pm', efficiency: 3})
hour = Hour.create({period: '4pm-5pm', efficiency: 4})
hour = Hour.create({period: '5pm-6pm', efficiency: 3})
hour = Hour.create({period: '6pm-7pm', efficiency: 2})
hour = Hour.create({period: '7pm-8pm', efficiency: 2})
hour = Hour.create({period: '8pm-9pm', efficiency: 2})
hour = Hour.create({period: '9pm-10pm', efficiency: 1})
hour = Hour.create({period: '10pm-11pm', efficiency: 3})
hour = Hour.create({period: '11pm-12am', efficiency: 3})

mary = User.create({name: "Mary"})
